version: "3"

services: 
    web:
        build: ./
        ports: 
            - "9002:9000"
        links: 
            - redis
    redis:
        image: redis
        container_name: cache
        expose:
            - 6379