

version: "3"

services: 
    web:
        build: ./
        ports: 
            - "9002:9000"
        environment: 
            - DOCKER_PORT=9002
        links: 
            - redis
    redis:
        image: redislabs/redisgraph
        container_name: cache
        expose: 
            - "6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
        external: false